import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        syne: ["Syne", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        figtree: ["Figtree", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        bg2: "hsl(var(--bg2))",
        bg3: "hsl(var(--bg3))",
        bg4: "hsl(var(--bg4))",
        text2: "hsl(var(--text2))",
        text3: "hsl(var(--text3))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        accent2: "hsl(var(--accent2))",
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        "nav-bg": "hsl(var(--nav-bg))",
        "sidebar-bg": "hsl(var(--sidebar-bg))",
        "btn-bg": "hsl(var(--btn-bg))",
        "btn-text": "hsl(var(--btn-text))",
        "sb-text": "hsl(var(--sb-text))",
        "sb-text-active": "hsl(var(--sb-text-active))",
        "sb-text-label": "hsl(var(--sb-text-label))",
        "sb-item-hover": "hsl(var(--sb-item-hover))",
        "sb-item-active": "hsl(var(--sb-item-active))",
        "sb-item-active-bar": "hsl(var(--sb-item-active-bar))",
        "sb-count-bg": "hsl(var(--sb-count-bg))",
        "sb-count-color": "hsl(var(--sb-count-color))",
        "sb-chip-bg": "hsl(var(--sb-chip-bg))",
        "sb-chip-border": "hsl(var(--sb-chip-border))",
        "sb-chip-color": "hsl(var(--sb-chip-color))",
        "tag-bg": "hsl(var(--tag-bg))",
        "tag-border": "hsl(var(--tag-border))",
        "tag-color": "hsl(var(--tag-color))",
        ai: "hsl(var(--ai))",
        danger: "hsl(var(--danger))",
        "code-bg": "hsl(var(--code-bg))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "var(--radius-sm)",
      },
      boxShadow: {
        card: "var(--shadow)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
